######################################
############# IMPORTANT ##############
# When upgrading the RuboCop gem,
# ensure that new cops do not heavily
# modify the existing style.
# Disable any of these new cops.
######################################
AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

# TODO: Please revert to 100!
Layout/LineLength:
  Max: 130

# Keep to syntactic linting, instead of complexity.
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# TODO: Please correct and remove!
Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/SelfAssignment:
  Enabled: false