AllCops:
  NewCops: disable

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# TEMPORARY
Metrics/BlockNesting:
  Enabled: false

Style/Documentation:
  Enabled: false
 
Lint/Debugger:
  Exclude:
    - "run.rb"

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 100

# Keep to syntactic linting, instead of complexity.
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Pending cops for RuboCop 0.80
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# Pendng cops for RuboCop 0.81
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true
